### ISSUE TITLE
media-gfx/openvdb-3.2.0: python documentation fails to compile

### ISSUE THREAD

**Issue by redchillipadi** [dracwyrm/gentoo-ebuilds#23]
Trying to test out the new ebuilds, so I will temporarily disable the docs and come back to this later

```
mkdir -p ${pydocdir}; \
echo "Created ${pydocdir}"; \
export LD_LIBRARY_PATH=:/var/tmp/portage/media-gfx/openvdb-3.2.0_pre20160604/work/openvdb-3.2.0_pre20160604/openvdb; \
export PYTHONPATH=:/var/tmp/portage/media-gfx/openvdb-3.2.0_pre20160604/work/openvdb-3.2.0_pre20160604/openvdb; \
    /usr/lib/python-exec/python3.5/pdoc --html --html-dir ${pydocdir} pyopenvdb > /dev/null
Created doc/html/python
python3.5: libs/python/src/converter/registry.cpp:212: void boost::python::converter::registry::insert(boost::python::converter::to_python_function_t, boost::python::type_info, const PyTypeObject* (*)()): Assertion `slot->m_to_python == 0' failed.
/bin/bash: line 5:  2676 Aborted                 /usr/lib/python-exec/python3.5/pdoc --html --html-dir ${pydocdir} pyopenvdb > /dev/null
Makefile:812: recipe for target 'pydoc' failed
make: *** [pydoc] Error 134
```

Build log:
[openvdb.log.txt](https://github.com/dracwyrm/gentoo-ebuilds/files/329922/openvdb.log.txt)

**Comment by dracwyrm** [comment]
It compiled for me. Did you try the newest pdoc update? I fixed a few issues with it. Also, I have boost 1.61 installed now to test things. It looks like a boost error, so it may need 1.61. When PDF Docs work for you, they don't work for me. When doc doesn't work for you, it works for me. haha. We have 100% opposite systems here.

**Comment by redchillipadi** [comment]
I am using boost-1.61 at the moment. I am using our pdoc-0.3.2 with changes from Gokturk's review.

**Comment by dracwyrm** [comment]
Strange. It built the docs just fine for me. Hmmm. We need to find out what the difference is. There may be a new dependency. If there is, then that will need to be added to the ebuild. I really like working with Pre ebuilds now as it gives us a chance to iron out things like this.

**Comment by redchillipadi** [comment]
This one is still an issue for me, I can't build openvdb with pdfdoc enabled.

**Comment by dracwyrm** [comment]
Yeah. I have no idea why this works for some, but not others. Worked for me. But then OSL docs didn't work for me. :P

**Comment by dracwyrm** [comment]
Same with the pdfdoc issue
